### Get all music
GET http://localhost:3000/musics
Accept: application/json
ACCESS_TOKEN: token_rahasia

### Get a music by id
GET http://localhost:3000/musics/2
Accept: application/json
ACCESS_TOKEN: token_rahasia

### Register user
POST http://localhost:3000/user/register
Accept: application/json
Content-Type: application/json

{
    "full_name": "anan",
    "username": "samnana",
    "password": "password1234",
    "gender": "laki"
}